# Generated by Django 3.2.19 on 2023-06-29 20:44

from django.db import migrations, models
import thebest.models


class Migration(migrations.Migration):

    dependencies = [
        ('thebest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='people',
            field=models.CharField(default='1', max_length=1, validators=[thebest.models.correct_people]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(default='5', max_length=2, validators=[thebest.models.correct_time]),
        ),
    ]
