# Generated by Django 3.2.19 on 2023-06-29 20:46

from django.db import migrations, models
import thebest.models


class Migration(migrations.Migration):

    dependencies = [
        ('thebest', '0003_auto_20230629_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='people',
            field=models.IntegerField(default='1', validators=[thebest.models.correct_people]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.IntegerField(default='5', validators=[thebest.models.correct_time]),
        ),
    ]
